import Head from "next/head";
import Image from "next/image";
import Menu from "@/Components/Menu";
import Link from "next/link";
import Header from "./Header";
import Footer from "./Footer";

export default function InnerPageLayout(props) {
  return (
    <>
      <Head>
        <title>{props.seotitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className="innerpage">
        <div className="bg_subheader">
          <div class="container pt-60 pb-5">
            <div className="title clr_green">{props.title}</div>
          </div>
        </div>

        <section className="py-5">{props.children}</section>
      </main>
      <Footer />
    </>
  );
}
