import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

import Header from "@/Components/Header";
import Footer from "@/Components/Footer";
import { useEffect } from "react";
import "aos/dist/aos.css";
import AOS from "aos";
import { Splide, SplideSlide } from "@splidejs/react-splide";
import "@splidejs/react-splide/css";
import testimonialsObj from "@/data/testimonials";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  useEffect(() => {
    AOS.init({
      duration: 2000,
    });
  }, []);

  return (
    <>
      <Head>
        <title>Smart Tech Asia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main>
        {/* banner section */}
        <section className="banner_section">
          {/* <div className="bg_banner">
            <Image src={"/images/bg-bw-blur.png"} fill={true} alt="Banner" />
          </div> */}
          <div className="">
            <div className="slider">
              {/* <Image src={"/images/banner1.png"} fill={true} alt="Banner" /> */}
              <Splide
                options={{
                  autoplay: true,
                  type: "loop",
                }}
                aria-label="My Favorite Images"
              >
                <SplideSlide>
                  <img
                    src="/images/slides/banner-1.jpg"
                    className="w-100"
                    alt="Authentication / Identification - Multiple Solutions - Mixtures"
                  />
                </SplideSlide>
                <SplideSlide>
                  <img
                    src="/images/slides/banner-2.jpg"
                    className="w-100"
                    alt="STA Registration"
                  />
                </SplideSlide>
                <SplideSlide>
                  <img
                    src="/images/slides/banner-3.jpg"
                    className="w-100"
                    alt="Aisle crowd"
                  />
                </SplideSlide>
                <SplideSlide>
                  <img
                    src="/images/slides/banner-4.jpg"
                    className="w-100"
                    alt="IMM Conference ISACA or Full house conference"
                  />
                </SplideSlide>
                <SplideSlide>
                  <img
                    src="/images/slides/banner-5.jpg"
                    className="w-100"
                    alt="Intel Dell Booth Pictures"
                  />
                </SplideSlide>
                <SplideSlide>
                  <img
                    src="/images/slides/banner-6.jpg"
                    className="w-100"
                    alt="Auto ID / Product Picture"
                  />
                </SplideSlide>
                <SplideSlide>
                  <img
                    src="/images/slides/banner-7.jpg"
                    className="w-100"
                    alt="Co-location"
                  />
                </SplideSlide>
              </Splide>
            </div>
          </div>
        </section>
        <img
          src="/images/show-highlisghts.jpg"
          className="w-100"
          alt="Show Highlights"
        />
        {/* <section className="highlight_section">
          
          <div className="container">
            <div className="bg_orange_light"></div>
            <div className="highlight_section_content">
              <h2 className="title">
                <strong className="clr_orange">Highlights</strong> of SmartTech
                Asia 2025
              </h2>

              <div className="d-flex justify-content-around mt_60">
                <div className="hg_box" data-aos="flip-up" data-aos-delay="100">
                  <span className="hg_count">100+</span>
                  <span className="hg_desc">Exhibitors</span>
                </div>
                <div className="hg_box" data-aos="flip-up" data-aos-delay="100">
                  <span className="hg_count">6000+</span>
                  <span className="hg_desc">Visitors</span>
                </div>
                <div className="hg_box" data-aos="flip-up" data-aos-delay="300">
                  <span className="hg_count">80+</span>
                  <span className="hg_desc">Speakers</span>
                </div>
                <div className="hg_box" data-aos="flip-up" data-aos-delay="500">
                  <span className="hg_count">200+</span>
                  <span className="hg_desc">Delegates</span>
                </div>
                <div className="hg_box" data-aos="flip-up" data-aos-delay="700">
                  <span className="hg_count">200+</span>
                  <span className="hg_desc">B2B Meetings</span>
                </div>
              </div>
            </div>
          </div>
        </section> */}

        <section className="about_section" style={{ marginTop: 0 }}>
          <div className="container">
            <div className="row">
              <div className="col-12 col-md-6">
                <div className="about_box">
                  <h3>Welcome to SmartTech Asia</h3>
                  <p>
                    SmartTech Asia Expo represents AI, IoT, RFID ,biometrics,
                    barcodes, digital payment, smart cards technologies. The
                    show has seen unprecedented success in the past two decades.
                    {/* <span className="read_more">Read More</span> */}
                  </p>
                  <p>
                    With the latest edition in Bengaluru, SmartTech Asia 2023
                    has successfully ventured into the next generation of smart
                    technology solutions. The event focusing on pioneering
                    solutions in AI, IoT, RFID ,biometrics, barcodes, digital
                    payment, smart cards technologies presented unmatched
                    networking opportunities and unlocked ample business
                    opportunities. The well-curated and knowledge-rich
                    conferences of the event brought together industry experts
                    to delve deep into the topics of emerging trends in
                    identity, accessibility and traceability management, and
                    increasing security risks of AI.
                  </p>
                </div>
                <span className="divider"></span>

                <div className="about_box mt-4">
                  <h3>Accompanying Programs</h3>
                  <p>
                    Smart Cards Expo host various programs with an aim to bring
                    together and inspire solution provider, practitioners and
                    decision makers and to share knowledge and experience that
                    pertains to proven and innovative environment.
                    <span className="read_more">Read More</span>
                  </p>
                </div>
              </div>
              <div className="col-12 col-md-6">
                <h2 className="title">
                  <strong className="clr_blue">Exhibition</strong> Video
                </h2>

                <div className="video_frame">
                  <iframe
                    width="100%"
                    height="315"
                    src="https://www.youtube.com/embed/JQ0lljdHu3c?si=qqOc4gUxfS4CDhN1&amp;controls=0"
                    title="YouTube video player"
                    frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    allowfullscreen
                  ></iframe>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="testimonials_section">
          <h2 className="title">
            <strong className="clr_blue">Testimonials</strong>
          </h2>
          <Splide
            className="testimonial_slider"
            options={{
              autoplay: true,
              type: "loop",
              perPage: 3,
              perMove: 1,
              breakpoints: {
                480: {
                  perPage: 1,
                  gap: ".7rem",
                  height: "6rem",
                },
              },
            }}
            aria-label="My Favorite Images"
          >
            {testimonialsObj.map((item) => (
              <SplideSlide>
                <div className="testimonial_box">
                  <div className="testimonial_text"><span>&ldquo;</span>{item.testimonial}&rdquo;</div>
                  <div className="d-flex mt-3">
                    <div>
                      <img
                        src={`/images/testimonials/${item.photo}`}
                        className="photo"
                        alt="testimonials"
                      />
                    </div>
                    <div>
                      <div className="testimonial_name">{item.name}</div>
                      <div className="testimonial_company_name">
                        {item.company_name}
                      </div>
                    </div>
                  </div>
                </div>
              </SplideSlide>
            ))}
          </Splide>
        </section>

        <section className="partner_section">
          <div className="container">
            {/* <h2 className="title">
              <strong className="clr_blue">Partners</strong>
            </h2> */}
            {/* <div className="row pt_40">
              <div className="col-12 col-md-2">
                <picture>
                  <img
                    src={"/images/placeholder1.png"}
                    className="w-100"
                    alt="Partner Logo"
                  />
                </picture>
              </div>
              <div className="col-12 col-md-2">
                <picture>
                  <img
                    src={"/images/placeholder1.png"}
                    className="w-100"
                    alt="Partner Logo"
                  />
                </picture>
              </div>
              <div className="col-12 col-md-2">
                <picture>
                  <img
                    src={"/images/placeholder1.png"}
                    className="w-100"
                    alt="Partner Logo"
                  />
                </picture>
              </div>
              <div className="col-12 col-md-2">
                <picture>
                  <img
                    src={"/images/placeholder1.png"}
                    className="w-100"
                    alt="Partner Logo"
                  />
                </picture>
              </div>
              <div className="col-12 col-md-2">
                <picture>
                  <img
                    src={"/images/placeholder1.png"}
                    className="w-100"
                    alt="Partner Logo"
                  />
                </picture>
              </div>
              <div className="col-12 col-md-2">
                <picture>
                  <img
                    src={"/images/placeholder1.png"}
                    className="w-100"
                    alt="Partner Logo"
                  />
                </picture>
              </div>
              <div className="col-12 col-md-2">
                <picture>
                  <img
                    src={"/images/placeholder1.png"}
                    className="w-100"
                    alt="Partner Logo"
                  />
                </picture>
              </div>
              <div className="col-12 col-md-2">
                <picture>
                  <img
                    src={"/images/placeholder1.png"}
                    className="w-100"
                    alt="Partner Logo"
                  />
                </picture>
              </div>
              <div className="col-12 col-md-2">
                <picture>
                  <img
                    src={"/images/placeholder1.png"}
                    className="w-100"
                    alt="Partner Logo"
                  />
                </picture>
              </div>
              <div className="col-12 col-md-2">
                <picture>
                  <img
                    src={"/images/placeholder1.png"}
                    className="w-100"
                    alt="Partner Logo"
                  />
                </picture>
              </div>
              <div className="col-12 col-md-2">
                <picture>
                  <img
                    src={"/images/placeholder1.png"}
                    className="w-100"
                    alt="Partner Logo"
                  />
                </picture>
              </div>
              <div className="col-12 col-md-2">
                <picture>
                  <img
                    src={"/images/placeholder1.png"}
                    className="w-100"
                    alt="Partner Logo"
                  />
                </picture>
              </div>
            </div> */}
            <div className="row ">
              <div className="col-12 col-md-12">
                <picture>
                  <img
                    src={"/images/partners.jpg"}
                    className="w-100"
                    alt="Partners"
                  />
                </picture>
              </div>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </>
  );
}
