import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Menu from "@/Components/Menu";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Smart Tech Asia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className="container">
          <div className="d-flex py-3">
            <div className="me-3">
              <Image
                src={"/images/logo.png"}
                width={214}
                height={124}
                alt="Logo"
              />
            </div>
            <div className="w-100">
              <div className="d-flex">
                <div className="fs_24  ">
                  <div className="show_info d-flex">
                    <span className="date">13-15</span>{" "}
                    <span className="month_year">
                      September
                      <br />
                      2023
                    </span>
                  </div>
                  <div className="venue">
                    India Expo Mart (IEML), <strong>Greater Noida</strong>
                  </div>
                </div>

                <div className="d-flex flex-fill justify-content-end">
                  <div className="text-center ms-3">
                    <small className="d-block mb-1">ORGANISER</small>
                    <Image
                      src={"/images/mm.png"}
                      width={110}
                      height={45}
                      alt="Logo"
                    />
                  </div>
                </div>
              </div>
              <div>
                <Menu />
              </div>
            </div>
          </div>
        </div>
      </header>

      <main>
        {/* banner section */}
        <section className="banner_section">
          <div className="bg_banner">
            <Image src={"/images/bg-bw-blur.png"} fill={true} alt="Banner" />
          </div>
          <div className="container pt_40">
            <div className="slider">
              <Image src={"/images/banner1.png"} fill={true} alt="Banner" />
            </div>
          </div>
        </section>

        <section className="highlight_section">
          <div className="container">
            <div className="bg_orange_light"></div>
            <div className="highlight_section_content">
              <h2 className="title">
                <strong className="clr_orange">Highlights</strong> of SmartTech
                Asia 2023
              </h2>

              <div className="d-flex justify-content-around mt_60">
                <div className="hg_box">
                  <span className="hg_count">100+</span>
                  <span className="hg_desc">
                    Top Solution <br />
                    Providers
                  </span>
                </div>
                <div className="hg_box">
                  <span className="hg_count">100+</span>
                  <span className="hg_desc">
                    Top Solution <br />
                    Providers
                  </span>
                </div>
                <div className="hg_box">
                  <span className="hg_count">100+</span>
                  <span className="hg_desc">
                    Top Solution <br />
                    Providers
                  </span>
                </div>
                <div className="hg_box">
                  <span className="hg_count">100+</span>
                  <span className="hg_desc">
                    Top Solution <br />
                    Providers
                  </span>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section></section>
        <section></section>
      </main>
    </>
  );
}
